# Generated by Django 4.1 on 2024-10-07 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0004_rename_name_category_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 7, 12, 5, 28, 694942)),
        ),
    ]
