# Generated by Django 4.1 on 2024-10-07 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0005_alter_food_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_img', models.ImageField(upload_to='')),
                ('short_discp', models.TextField()),
                ('title', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='food',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 7, 12, 45, 42, 922852)),
        ),
    ]
