# Generated by Django 4.1 on 2024-10-09 05:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0007_alter_banner_banner_img_alter_food_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_colour',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 9, 10, 58, 15, 717661)),
        ),
    ]
